### ISSUE TITLE
Very weird issue with raymond/handlebars template

### ISSUE THREAD

**Issue by adarqui** [kataras/go-template#12]
Hey, i'm having the weirdest issue. The iris + handlebars templates work fine on my OSX machine. But they don't work on  Linux machine. It makes no sense though, it's the raymond.SafeString() function.

```
import (
  "github.com/aymerick/raymond"
  "testing"
)

func TestSafeString(t *testing.T) {
  s := raymond.SafeString("wtf&")
  if s != "wtf&" {
    t.Fatal("raymond is broken")
  }
  e := raymond.Escape("wtf&")
  if e != "wtf&amp;" {
    t.Fatal("raymond is broken")
  }
}
```

I have that test on my OSX and Linux machines.. They both work/pass. However, when I load up my site on the linux server, I get the escaped string in the web response:

So i'll see:

```wtf&amp;``

instead of:

```wtf&```

Go on linux: 1.7.5
Go on OSX: 1.7.4

Iris on linux: 6.1.4
Iris on OSX: 6.1.2

I haven't been able to figure it out for a few hours.. so posting the issue. Any help would be greatly appreciated. It makes absolutely no sense to me. It's almost as if the safe string i'm adding to my map[string]interface{} is "losing the Type information" and just becoming a normal string, which is escaped.. or something.

Edit: I can confirm that the value in my map is entering the Render function as a SafeString .. But once it hits:

ctx.Render(template, my_map)

After it hits Render, somehow it's turning into an escaped string.

So literally this isn't working properly on linux, but works on osx:

```
m := make(map[string]interface{})
m["blah"] = raymond.SafeString("wtf&")
ctx.Render(template, m)
```

Thanks

**Comment by adarqui** [comment]
Odd .. I think I figured it out, but I don't get it.

I used {{{Blah}}} instead of {{Blah}}, and now it's working on Linux.. But {{Blah}} works fine on OSX.

Weird.. Any idea?

Thanks!

**Comment by kataras** [comment]
Hello @adarqui , thanks for posting.

I really don't know what's going on with that issue, but I'm sure that it's not specific to this package, this repository contains a common interface for all known golang template parses. It should be template parser's issue(?) and you should ask that question [there](https://github.com/aymerick/raymond/issues/new) if you want to get a fix or an answer.

Link this issue to your post [there](https://github.com/aymerick/raymond/issues/new) in order to be notified for any changes which I may need to do here too.

Thanks,
kataras

**Comment by adarqui** [comment]
Thank you. I'm closing this for now, fixed by using triple brackets: {{{blah}}}
